import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
const quickSand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GoogleOAuthProvider clientId="43129710881-44gu9okv7r1vbtbomiudq9jbv4p0l3ob.apps.googleusercontent.com">
      <html lang="en">
        <body className={quickSand.className}>{children}</body>
      </html>
    </GoogleOAuthProvider>
  );
}
